import Header from './header';
import Footer from './footer';
import Sidebar from "./sidebar";
import React, { Fragment, useState } from "react";

export default function AppLayout({children, title="Sample Title"}) {
  const [mobileNavsidebar, setMobileNavsidebar] = useState(false);
  return (
    <>
      {/* <head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head> */}

      <div className="flex bg-gray-100 min-h-screen relative">
        <Sidebar mobileNavsidebar={mobileNavsidebar} />
        <div className="flex-grow text-gray-800">
          <Header mobileNavsidebar={mobileNavsidebar} setMobileNavsidebar={setMobileNavsidebar} />
          {children}
        </div>

        <Footer />
      </div>
    </>
  );
}
